WebApp/Models/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models.ViewModels;

public class LoginViewModel
{
    [Required]
    [EmailAddress]
    public string Email { get; set; } = null!;


    [Required]
    [DataType(DataType.Password)]
    public string Password { get; set; } = null!;


    [Display(Name = "Remember me?")]
    public bool RememberMe { get; set; } = false;
}

WebApp/Models/ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;
using WebApp.Models.Entities;

namespace WebApp.Models.ViewModels;

public class RegisterViewModel
{
    [Required]
    public string FirstName { get; set; } = null!;
    [Required]
    public string LastName { get; set; } = null!;

    [Required(ErrorMessage = "You must provide an e-mail address.")]
    [DataType(DataType.EmailAddress)]
    [RegularExpression(@"^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$", ErrorMessage = "Invalid email format.")]
    public string Email { get; set; } = null!;
    [Required(ErrorMessage = "You must provide a password.")]
    [DataType(DataType.Password)]
    [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$", ErrorMessage = "Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter and one number")]
    public string Password { get; set; } = null!;
    [Required(ErrorMessage ="You must confirm your password.")]
    [DataType(DataType.Password)]
    [Compare("Password", ErrorMessage = "Passwords do not match")]
    public string ConfirmPassword { get; set; } = null!;
    public string StreetName { get; set; } = null!;
    public string PostalCode { get; set; } = null!;
    public string City { get; set; } = null!;

    public static implicit operator UserEntity(RegisterViewModel model)
    {
        return new UserEntity()
        {
            FirstName = model.FirstName, 
            LastName = model.LastName, 
            Email = model.Email, 
            UserName = model.Email 
        };
    }

    public static implicit operator AddressEntity(RegisterViewModel model)
    {
        return new AddressEntity()
        {
            StreetName = model.StreetName, 
            PostalCode = model.PostalCode, 
            City = model.City
        };
    }
}

WebApp/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Helpers.Repositories;
using WebApp.Models.ViewModels;

namespace WebApp.Controllers
{
    public class ContactsController : Controller
    {
        private readonly ContactFormRepository _contactFormViewModel;

        public ContactsController(ContactFormRepository contactFormViewModel)
        {
            _contactFormViewModel = contactFormViewModel;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactFormViewModel viewModel)
        {
            if(ModelState.IsValid)
            {
                await _contactFormViewModel.AddAsync(viewModel);
                return RedirectToAction(nameof(Index));
            }

            return View(viewModel);
        }
    }
}

WebApp/Controllers/LoginController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApp.Helpers.Services;
using WebApp.Models.ViewModels;

namespace WebApp.Controllers;

public class LoginController : Controller
{
    private readonly AuthenticationService _authenticationService;

    public LoginController(AuthenticationService authenticationService)
    {
        _authenticationService = authenticationService;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Index(LoginViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            if (await _authenticationService.LoginAsync(viewModel))
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Incorrect email or password!");
            }
        }
        return View(viewModel);
    }
}

WebApp/Controllers/LogoutController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models.Entities;

namespace WebApp.Controllers
{

    
    public class LogoutController : Controller
    {
        private readonly SignInManager<UserEntity> _signInManager;

        public LogoutController(SignInManager<UserEntity> signInManager)
        {
            _signInManager = signInManager;
        }

        public async Task<IActionResult> Index()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home"); // Redirect to home page

        }
    }
}

WebApp/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers;

public class ProductsController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Search()
    {
        return View();
    }

    public IActionResult Details(int id)
    {
        return View(id);
    }
}

WebApp/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApp.Helpers.Services;
using WebApp.Models.Entities;
using WebApp.Models.ViewModels;

namespace WebApp.Controllers;

public class RegisterController : Controller
{
    private readonly UserManager<UserEntity> _userManager;
    private readonly AuthenticationService _authenticationService;

    public RegisterController(UserManager<UserEntity> userManager, AuthenticationService authenticationService)
    {
        _userManager = userManager;
        _authenticationService = authenticationService;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Index(RegisterViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            if (!await _userManager.Users.AnyAsync(u => u.Email == viewModel.Email))
            {
                if (await _authenticationService.RegisterAsync(viewModel))
                    return RedirectToAction("Index", "Login");
            }
            else
            {
                ModelState.AddModelError("", "A user with that email already exists.");
            };
        }
        return View(viewModel);
    }
}

WebApp/Controllers/UnitEntitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Contexts;
using WebApp.Models.Entities;
using WebApp.Models.ViewModels;

namespace WebApp.Controllers
{
    public class UnitEntitiesController : Controller
    {
        private readonly DataContext _context;

        public UnitEntitiesController(DataContext context)
        {
            _context = context;
        }

        // GET: UnitEntities/Search
        public async Task<IActionResult> Index(string unitCategory, string searchString)
        {
            if (_context.UnitEntity == null)
            {
                return Problem("Entity set 'DataContext.UnitEntity'  is null.");
            }

            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from m in _context.UnitEntity
                                            orderby m.Category
                                            select m.Category;
            var unites = from m in _context.UnitEntity
                         select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                unites = unites.Where(s => s.Title!.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(unitCategory))
            {
                unites = unites.Where(x => x.Category == unitCategory);
            }

            var unitCategoryVM = new UnitCategoryViewModel
            {
                Categories = new SelectList(await genreQuery.Distinct().ToListAsync()),
                Units = await unites.ToListAsync()
            };

            return View(unitCategoryVM);
        }



        // GET: UnitEntities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.UnitEntity == null)
            {
                return NotFound();
            }

            var unitEntity = await _context.UnitEntity
                .FirstOrDefaultAsync(m => m.Id == id);
            if (unitEntity == null)
            {
                return NotFound();
            }

            return View(unitEntity);
        }

        // GET: UnitEntities/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UnitEntities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Ingress,ImageUrl,Price,Category")] UnitEntity unitEntity)
        {
            if (ModelState.IsValid)
            {
                _context.Add(unitEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(unitEntity);
        }

        // GET: UnitEntities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.UnitEntity == null)
            {
                return NotFound();
            }

            var unitEntity = await _context.UnitEntity.FindAsync(id);
            if (unitEntity == null)
            {
                return NotFound();
            }
            return View(unitEntity);
        }

        // POST: UnitEntities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Ingress,ImageUrl,Price,Category")] UnitEntity unitEntity)
        {
            if (id != unitEntity.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(unitEntity);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UnitEntityExists(unitEntity.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(unitEntity);
        }

        // GET: UnitEntities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.UnitEntity == null)
            {
                return NotFound();
            }

            var unitEntity = await _context.UnitEntity
                .FirstOrDefaultAsync(m => m.Id == id);
            if (unitEntity == null)
            {
                return NotFound();
            }

            return View(unitEntity);
        }

        // POST: UnitEntities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.UnitEntity == null)
            {
                return Problem("Entity set 'DataContext.UnitEntity'  is null.");
            }
            var unitEntity = await _context.UnitEntity.FindAsync(id);
            if (unitEntity != null)
            {
                _context.UnitEntity.Remove(unitEntity);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UnitEntityExists(int id)
        {
          return (_context.UnitEntity?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApp/Views/Partials/_BestCollection.cshtml
<section class="best-collection">
    <div class="container">
        <h1 class="collection-title">Best Collection</h1>
        <ul class="categories">
            <li class="category-item">All</li>
            <li class="category-item">Bag</li>
            <li class="category-item">Dress</li>
            <li class="category-item">Decoration</li>
            <li class="category-item">Essentials</li>
            <li class="category-item">Interior</li>
            <li class="category-item">Laptop</li>
            <li class="category-item">Mobile</li>
            <li class="category-item">Beaty</li>
        </ul>
        <div class="collection-grid">

            <!-- collection-item start -->
            <a asp-controller="unitEntities" asp-action="Index" class="collection-item">
                <img src="images/placeholders/270x295.jpg" alt="">
                <div class="body">
                    <div class="title">Headphone collection</div>
                    <div class="info">
                        <div class="price">$30.00</div>
                        <i class="add-cart fa-regular fa-cart-plus"></i>
                    </div>
                </div>
            </a>
            <!-- collection-item end -->
            <!-- collection-item start -->
            <a asp-controller="unitEntities" asp-action="Index" class="collection-item">
                <img src="images/placeholders/270x295.svg" alt="">
                <div class="body">
                    <div class="title">Headphone collection</div>
                    <div class="info">
                        <div class="price">$30.00</div>
                        <i class="add-cart fa-regular fa-cart-plus"></i>
                    </div>
                </div>
            </a>
            <!-- collection-item end -->
            <!-- collection-item start -->
            <a href="#" class="collection-item">
                <img src="images/placeholders/270x295.svg" alt="">
                <div class="body">
                    <div class="title">Headphone collection</div>
                    <div class="info">
                        <div class="price">$30.00</div>
                        <i class="add-cart fa-regular fa-cart-plus"></i>
                    </div>
                </div>
            </a>
            <!-- collection-item end -->
            <!-- collection-item start -->
            <a href="#" class="collection-item">
                <img src="images/placeholders/270x295.svg" alt="">
                <div class="body">
                    <div class="title">Headphone collection</div>
                    <div class="info">
                        <div class="price">$30.00</div>
                        <i class="add-cart fa-regular fa-cart-plus"></i>
                    </div>
                </div>
            </a>
            <!-- collection-item end -->
            <!-- collection-item start -->
            <a href="#" class="collection-item">
                <img src="images/placeholders/270x295.svg" alt="">
                <div class="body">
                    <div class="title">Headphone collection</div>
                    <div class="info">
                        <div class="price">$30.00</div>
                        <i class="add-cart fa-regular fa-cart-plus"></i>
                    </div>
                </div>
            </a>
            <!-- collection-item end -->
            <!-- collection-item start -->
            <a href="#" class="collection-item">
                <img src="images/placeholders/270x295.svg" alt="">
                <div class="body">
                    <div class="title">Headphone collection</div>
                    <div class="info">
                        <div class="price">$30.00</div>
                        <i class="add-cart fa-regular fa-cart-plus"></i>
                    </div>
                </div>
            </a>
            <!-- collection-item end -->
            <!-- collection-item start -->
            <a href="#" class="collection-item">
                <img src="images/placeholders/270x295.svg" alt="">
                <div class="body">
                    <div class="title">Headphone collection</div>
                    <div class="info">
                        <div class="price">$30.00</div>
                        <i class="add-cart fa-regular fa-cart-plus"></i>
                    </div>
                </div>
            </a>
            <!-- collection-item end -->
            <!-- collection-item start -->
            <a href="#" class="collection-item">
                <img src="images/placeholders/270x295.svg" alt="">
                <div class="body">
                    <div class="title">Headphone collection</div>
                    <div class="info">
                        <div class="price">$30.00</div>
                        <i class="add-cart fa-regular fa-cart-plus"></i>
                    </div>
                </div>
            </a>
            <!-- collection-item end -->

        </div>
        <div class="load-more">
            <button class="btn-outline-white">LOAD MORE <i class="fa-solid fa-rotate-right"></i></button>
        </div>
    </div>
</section>

WebApp/Views/Partials/_Breadcrumb.cshtml
<section class="breadcrumb">
    <div class="container">
        <div class="content">
            <h1>CONTACT</h1>
            <ul>
                <li>HOME</li>
                <li>CONTACT</li>
            </ul>
        </div>
    </div>
</section>

WebApp/Views/Partials/_ContactForm.cshtml
@model ContactFormViewModel

<section class="contact-form">
    <div class="container">
        <div class="title">Please write a message to us.</div>
        <form asp-action="Index" asp-controller="Contacts" method="post" novalidate>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="name form-group">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" onkeyup="validateText(event)" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="email form-group">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" type="email" class="form-control" onkeyup="validateEmail(event)" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="phoneNumber form-group">
                <label for="phone">Phone Number (optional)</label>
                <input id="phone" type="text">
            </div>
            <div class="companyName form-group">
                <label for="company">Company (optional)</label>
                <input id="company" type="text">
            </div>
            <div class="message form-group">
                <label asp-for="Message" class="form-label"></label>
                <textarea asp-for="Message" class="form-control" rows="3" onkeyup="validateText(event)"></textarea>
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
@*            <div class="terms form-checkbox-group">
                <label class="custom-checkbox">
                    Save my name, email in the this browser for the next time I comment.
                    <input type="checkbox" checked="checked">
                    <span class="checkmark"></span>
                </label>
            </div>*@
            <button type="submit" class="btn btn-primary">Send</button>
        </form>
    </div>
</section>

WebApp/Views/Partials/_Footer.cshtml
<footer>
    <div class="container">
        © @DateTime.Now.Year bmerketo. All right reserved.
    </div>
</footer>

WebApp/Views/Partials/_Header.cshtml
@inject SignInManager<UserEntity> signInManager

<header>
    <div class="container">
        <div class="logo"><img src="images/logo.svg" alt="">bmerketo</div>
        <nav id="menu" class="menu-links">
            <a class="link" asp-controller="Home" asp-action="Index">HOME</a>
@*            <a class="link" asp-controller="Products" asp-action="Index">PRODUCTS</a>*@
            <a class="link" asp-controller="UnitEntities" asp-action="Index">unitPRODUCTS</a>
            <a class="link" asp-controller="Contacts" asp-action="Index">CONTACT</a>
        </nav>
        <nav class="menu-icons">
            <a class="link" asp-controller="UnitEntities" asp-action="Index"><i class="fa-regular fa-search"></i></a>
@*            <a class="link" asp-controller="Products" asp-action="Search"><i class="fa-regular fa-search"></i></a>*@
            <a class="link" asp-controller="unitEntities" asp-action="Index"><i class="fa-solid fa-cart-shopping"></i></a>

            @if (signInManager.IsSignedIn(User))
            {
                <a class="link" asp-controller="account" asp-action="Index">@User.Identity?.Name</a>
                
                if (User.IsInRole("Admin"))
                {
                    <a class="link" asp-controller="Admin" asp-action="Index">BackOffice</a>
                }
                <a class="link" asp-action="Index" asp-controller="Logout">Logout</a>
            }
            else
            {
                <a class="link" asp-controller="Login" asp-action="Index">Login</a>
            }
        </nav>
        <div class="toggle">
            <button class="btn-toggle btn-outline-white" data-option="toggle" data-target="#menu">
                <i id="icon" class="fa-regular fa-bars"></i>
            </button>
        </div>
    </div>
</header>

WebApp/Views/Partials/_Login.cshtml
@model LoginViewModel

<section class="contact-form">
    <div class="container">
        <div class="title">Please login.
        <a class="link" asp-controller="Register" asp-action="Index">Don´t have an account? Create one here!</a>
        </div>
        <form asp-action="Index" asp-controller="Login" method="post" novalidate>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="email form-group">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" type="email" class="form-control" onkeyup="validateEmail(event)" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="password form-group">
                <label asp-for="Password" class="form-label"></label>
                <input asp-for="Password" type="password" class="form-control" onkeyup="validatePassword(event)" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</section>

WebApp/Views/Partials/_Map.cshtml
<section class="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2131.3153063389127!2d11.943946912574125!3d57.71110167376252!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x464ff3bcaf2710d9%3A0x438092abc7ede5ab!2sEC%20Utbildning!5e0!3m2!1ssv!2sse!4v1685178517076!5m2!1ssv!2sse" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</section>

WebApp/Views/Partials/_Newsletter.cshtml
<section class="newsletter">
    <div class="container">
        <form>
            <input type="text" placeholder="subscribe mail here..." maxlength="64">

            <button class="btn-theme btn-rounded"><i class="fa-sharp fa-solid fa-paper-plane fa-beat"></i></button>
        </form>
    </div>
</section>

WebApp/Views/Partials/_Register.cshtml
@model RegisterViewModel

<section class="contact-form">
    <div class="container">
        <div class="title">Please register a account.</div>
        <form asp-action="Index" asp-controller="Register" method="post" novalidate>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="firstname form-group">
                <label asp-for="FirstName" class="form-label"></label>
                <input asp-for="FirstName" class="form-control" onkeyup="validateText(event)"/>
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="lastname form-group">
                    <label asp-for="LastName" class="form-label"></label>
                <input asp-for="LastName" class="form-control" onkeyup="validateText(event)" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="email form-group">
                    <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" type="email" class="form-control" onkeyup="validateEmail(event)" />
                    <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="password form-group">
                    <label asp-for="Password" class="form-label"></label>
                <input asp-for="Password" type="password" class="form-control" onkeyup="validatePassword(event)" />
                    <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="confirmpassword form-group">
                    <label asp-for="ConfirmPassword" class="form-label"></label>
                <input asp-for="ConfirmPassword" type="password" class="form-control" onkeyup="validatePassword(event)" />
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="streetname form-group">
                <label asp-for="StreetName" class="form-label"></label>
                <input asp-for="StreetName" class="form-control" onkeyup="validateText(event)" />
                <span asp-validation-for="StreetName" class="text-danger"></span>
            </div>
            <div class="postalcode form-group">
                <label asp-for="PostalCode" class="form-label"></label>
                <input asp-for="PostalCode" class="form-control" onkeyup="validatePostalCode(event)" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="city form-group">
                <label asp-for="City" class="form-label"></label>
                <input asp-for="City" class="form-control" onkeyup="validateText(event)" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</section>

WebApp/Views/Partials/_ShowCase.cshtml
<section class="showcase">
    <div class="container">
        <div class="content">
            <div class="ingress">WELCOME TO BMERKETO SHOP</div>
            <div class="title">Exclusive Chair gold Collection.</div>



            <button class="btn-theme" onclick="location.href='@Url.Action("Index", "UnitEntities")'">SHOP NOW</button>

        </div>
        <div class="content-image">
            <img src="images/placeholders/625x647.jpg" alt="">
        </div>
    </div>
</section>

WebApp/Views/Partials/_UpToSale.cshtml
<section class="up-to-sale">
    <div class="container">
        <div class="collection-grid">
            <div class="item-1">
                <!-- collection-item start -->
                <a asp-controller="unitEntities" asp-action="Index" class="collection-item">
                    <img src="images/placeholders/369x310.jpg" alt="">
                    <div class="body">
                        <div class="title">Headphone collection</div>
                        <div class="info">
                            <div class="price">$30.00</div>
                            <i class="add-cart fa-regular fa-cart-plus"></i>
                        </div>
                    </div>
                </a>
                <!-- collection-item end -->
            </div>
            <div class="discover">
                <!-- collection-content start -->
                <div class="collection-content">
                    <div class="container">
                        <div class="title-red">UP TO SALE</div>
                        <div class="title">50% OFF</div>
                        <div class="ingress">Get the Best Price</div>
                        <div class="text">Get the best daily offer et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren no sea taki</div>
                        <a href="#" class="link">Discover More</a>
                    </div>
                </div>
                <!-- collection-content end -->
            </div>
            <div class="item-2">
                <!-- collection-item start -->
                <a href="#" class="collection-item">
                    <img src="images/placeholders/369x310.svg" alt="">
                    <div class="body">
                        <div class="title">Headphone collection</div>
                        <div class="info">
                            <div class="price">$30.00</div>
                            <i class="add-cart fa-regular fa-cart-plus"></i>
                        </div>
                    </div>
                </a>
                <!-- collection-item end -->
            </div>
        </div>
    </div>
</section>